language: ruby
rvm:
  - 2.0.0
  - 2.2.1
  - 2.3.7
services:
  - postgres
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database website_test;' -U postgres
env:
  global:
    - POSTGRES_PORT_5432_TCP_ADDR=localhost
    - POSTGRES_PORT_5432_TCP_PORT=5432
    - POSTGRES_ENV_POSTGRES_DB=website_test
    - POSTGRES_ENV_POSTGRES_PASSWORD=
    - AUTH_USERNAME=admin
    - AUTH_PASSWORD=admin
