language: ruby
rvm:
  - 2.2.1
    
before_script:
  - mysql -e 'create database website_test;'

env:
  global:
    - MYSQL_PORT_3306_TCP_ADDR=127.0.0.127
    - MYSQL_PORT_3306_TCP_PORT=3306
    - MYSQL_ENV_MYSQL_DATABASE=website_test
    - MYSQL_ENV_MYSQL_ROOT_PASSWORD=